### ISSUE TITLE
[BUG] Custom theme does not work in TOML

### ISSUE THREAD

**Issue by springcomp** [SoMuchForSubtlety/f1viewer#207]
Please check the [FAQ](https://github.com/SoMuchForSubtlety/f1viewer#Faq) and search [existing issues](https://github.com/SoMuchForSubtlety/f1viewer/issues?q=is%3Aissue) before you submit a new one!

**Describe the bug**

Before upgrading to the latest version my `config.json` looked like this:

```json
{
	"theme": {
		"action_node_color": "#ffb27f",
		"background_color": "#012456",
		"border_color": "",
		"category_node_color": "#ae4cff",
		"error_color": "",
		"folder_node_color": "#ff5d00",
		"info_color": "",
		"item_node_color": "#9efffa",
		"live_color": "#ff006e",
		"loading_color": "#115411",
		"multi_command_color": "",
		"no_content_color": "#7f92ff",
		"terminal_accent_color": "",
		"terminal_text_color": "#b7b29a",
		"update_color": "#ff00dc"
	}
}
```

I have sucessfully downloaded the latest version from GitHub releases and on first launch it converted the configuration file to `config.toml`. However, it did not convert the custom them. So I reproduced the values like so:

```toml
# you can override the default colours by providing new values in hex format (#RRGGBB)
[theme]
  action_node_color     = "#FFB27F"
  background_color      = "#012456"
  border_color          = ""
  category_node_color   = "#AE4CFF"
  error_color           = ""
  folder_node_color     = "#FF5D00"
  info_color            = ""
  item_node_color       = "#9EFFFA"
  live_color            = "#FF006E"
  loading_color         = "#115411"
  multi_command_color   = ""
  no_content_color      = "#7F92FF"
  terminal_accent_color = ""
  terminal_text_color   = "#B7B29A"
  update_color          = "#FF00DC"
```
I used spaces instead of tab characters and aligned all the values to reproduce the sample theme.
However, none of those colors work.

**Screenshots**

This is a screenshot with the custom colors applied. It has absolutely no difference with either the default theme provided, or the theme completely removed from the configuration file.

![image](https://user-images.githubusercontent.com/8488398/158012801-79409a1e-f408-4f5d-86ea-d181d2da1bef.png)

In particular, menu entries are not legible with my default terminal background.

**F1TV account plan**
F1TV Pro

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - installation method : manual download from GitHub releases.
 - Version [`f1viewer -v` output]

```
Version:     2.5.0
Git commit:  aad74d9eeea99096b5b25cc0f82666d023671076
Built:       2021-12-01T17:51:11Z
```

**Logs**
If applicable please provide the relevant portion of your logs. You can find them by running `f1viewer -logs`.
